# PlatformIO pre-build hook: keep the firmware build date fresh.
#
# fw_version.cpp reports FW_BUILD_DATE, which the web UI compares against the GitHub
# release date to decide "up to date / update available". The old approach (touch
# fw_version.cpp so __DATE__ recompiles) silently never worked: SCons decides rebuilds
# by CONTENT hash, not mtime, so the object was reused and the stamp froze — every
# build from Jul 21 to Aug 15 2026 reported "Jul 21 2026". Instead, generate the date
# into a header (gitignored) — the content changes once per day, so the translation
# unit recompiles exactly once per day and the reported date can never go stale.
#
# The literal matches __DATE__'s format ("Mmm dd yyyy", day space-padded, English
# month) because the web UI and any cached parsing expect exactly that shape.
#
# Inherited by env:loopster-release via `extends` (release overrides only build_flags),
# so customer builds get an accurate date too.
Import("env")
import datetime
import os

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]  # C locale, never the OS locale

now = datetime.date.today()
stamp = "%s %2d %d" % (MONTHS[now.month - 1], now.day, now.year)
content = (
    "// GENERATED by version_stamp.py before every build — do not edit, not tracked.\n"
    '#define FW_BUILD_DATE_LIT "%s"\n' % stamp
)

path = os.path.join(env.subst("$PROJECT_SRC_DIR"), "fw_build_date.h")
try:
    with open(path) as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False
if not unchanged:  # write only on change: same-day rebuilds stay incremental
    with open(path, "w") as f:
        f.write(content)
